spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5433/apirest
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
